### ISSUE TITLE
What can I do to catch TimeoutError Exception ?

### ISSUE THREAD

**Issue by Alienboyplus** [scrapy-plugins/scrapy-playwright#111]
Hi !

I tried to add my proxy in my `mainSpider.py` file like this and it works:
```python
return scrapy.Request(
    url=url,
    cookies=cookies,
    meta={
        "proxy_str": proxy_str,
        "playwright": True,
        "playwright_include_page": True,
        "playwright_context": uuid.uuid1(),
        "playwright_context_kwargs": {
            "storage_state": {
                "cookies": cookies,
            },
            "proxy": proxy

        }
    },
)
```
But some of my proxies are bad. They can't connect to the internet. Here is the log (I use [target website] to swap the original website):
```
2022-07-26 10:13:13 [scrapy-playwright] DEBUG: Browser context started: '8093363c-0c88-11ed-ac8b-5254004c98ad'
2022-07-26 10:13:43 [scrapy.core.scraper] ERROR: Error downloading <GET [target website]>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1657, in _inlineCallbacks
    cast(Failure, result).throwExceptionIntoGenerator, gen
  File "/usr/local/python3/lib/python3.7/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/core/downloader/middleware.py", line 49, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/usr/local/python3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1030, in adapt
    extracted = result.result()
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy_playwright/handler.py", line 147, in _download_request
    result = await self._download_request_with_page(request, page)
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy_playwright/handler.py", line 158, in _download_request_with_page
    response = await page.goto(request.url)
  File "/usr/local/python3/lib/python3.7/site-packages/playwright/async_api/_generated.py", line 7604, in goto
    url=url, timeout=timeout, waitUntil=wait_until, referer=referer
  File "/usr/local/python3/lib/python3.7/site-packages/playwright/_impl/_page.py", line 493, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/usr/local/python3/lib/python3.7/site-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/local/python3/lib/python3.7/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/python3/lib/python3.7/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "[target website]", waiting until "load"
============================================================
```
It is actually caused by the proxies, not the scrapy-playwright. **But I want to know how to catch these exceptions.**

It would be better if I don't have to edit the Scrpy & scrapy-playwright Python files.

Can I catch them in my  `mainSpider.py`  file ?

**Comment by elacuesta** [comment]
Exceptions are handled just like with regular Scrapy, e.g. with request errbacks and spider middlewares. See the `exception_errback.py` and `exception_middleware.py` files at the `examples` directory.
