### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by yswtrue** [scrapy-plugins/scrapy-playwright#116]
```
Traceback (most recent call last):
  File "/home/yswtrue/Code/stock_scraper/.venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/yswtrue/Code/stock_scraper/.venv/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/yswtrue/Code/stock_scraper/.venv/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 49, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/home/yswtrue/Code/stock_scraper/.venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 1030, in adapt
    extracted = result.result()
  File "/home/yswtrue/Code/stock_scraper/.venv/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 275, in _download_request
    result = await self._download_request_with_page(request, page)
  File "/home/yswtrue/Code/stock_scraper/.venv/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 314, in _download_request_with_page
    server_ip_address = ip_address(server_addr["ipAddress"])
TypeError: 'NoneType' object is not subscriptable
```

launch with `user_data_dir`
```
            yield scrapy.Request(
                url=url,
                dont_filter=True,
                callback=self.check_login,
                headers=self.headers,
                meta={
                    "account_info": account_info,
                    "playwright": True,
                    "playwright_context": f"{account_info['username']}context",
                    "playwright_page_goto_kwargs": {
                        "wait_until": "domcontentloaded",
                    },
                    "playwright_include_page": True,
                    "playwright_context_kwargs": {
                        # "java_script_enabled": False,
                        "headless": False,
                        "ignore_https_errors": True,
                        "user_data_dir": f"data/{account_info['username']}",
                        "proxy": {
                            "server": proxy_url,
                            "username": user or "",
                            "password": password or "",
                        }
                        if proxy
                        else None,
                    },
                },
                # meta={
                #     "proxy": self.proxy if self.proxy else None,
                # },
            )

```

**Comment by elacuesta** [comment]
Fixed in 6ddd4bdc315cc7bddfe1d17b4592bd5203777354, released as [v0.0.21](https://github.com/scrapy-plugins/scrapy-playwright/releases/tag/v0.0.21). Thanks for the report.
