### ISSUE TITLE
Scrapy process consume high memory and it keeps going up.

### ISSUE THREAD

**Issue by gurmitteotia** [scrapy-plugins/scrapy-playwright#126]
I encountered the issue where scrapy crawler memory consumption was increasing significantly when using with scrapy-playwright plugin. On painfull debugging I found out that my issue is related
to  [issue](https://github.com/microsoft/playwright/issues/6319). As it is being suggested in #19  a quick solution will be create  page per context and close the context and page after receiving the requests and that resolve the memory issue for me. However I keep getting lots of browser/context closed error, below are some examples of stack traces-

Error 1
```
ERROR:asyncio:Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...been closed')>) at /home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/pyee/_asyncio.py:55
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...been closed')>) at /home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/pyee/_asyncio.py:55>
Traceback (most recent call last):
  File "/home/zzz/anaconda3/envs/crawler/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/pyee/_asyncio.py", line 62, in _callback
    self.emit('error', exc)
  File "/home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/pyee/_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "/home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/scrapy_playwright/handler.py", line 441, in _log_request
    referrer = await request.header_value("referer")
  File "/home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 355, in header_value
    return mapping.from_maybe_impl(await self._impl_obj.header_value(name=name))
  File "/home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/playwright/_impl/_network.py", line 198, in header_value
    return (await self._actual_headers()).get(name)
  File "/home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/playwright/_impl/_network.py", line 206, in _actual_headers
    headers = await self._channel.send("rawRequestHeaders")
  File "/home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 387, in wrap_api_call
    return await cb()
  File "/home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
```

Error 2
```
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-7838' coro=<ScrapyPlaywrightDownloadHandler._make_request_handler.<locals>._request_handler() running at /home/zzz/anaconda3/envs/crawler/lib/python3.8/site-packages/scrapy_playwright/handler.py:405> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f14a5a045b0>()]> cb=[gather.<locals>._done_callback() at /home/zzz/anaconda3/envs/crawler/lib/python3.8/asyncio/tasks.py:769]>
```
I'm using following spider to close the context and page after receiving the response.

```
class TestSpider(scrapy.Spider):
    name = 'test_all'
    def __init__(self, settings, **kwards):
        super(TestSpider, self).__init__(**kwards)
        url = settings.get('URL','')
        
    @classmethod
    def from_settings(cls, settings, **kwards):
        return cls(settings, **kwards)

    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs):
        obj = cls.from_settings(crawler.settings, **kwargs)
        obj.crawler = crawler
        return obj

    async def parse_response(self, response, **kwards):
       
        try:
            item = CrawlerItem()
            item['crawled_page']= response.text
            yield item

            for  child_link in self._links(response.text):
                yield self._build_request(child_link)
        except Exception:
            self.logger.exception("Failed to parse the response for page %s", response.url)
        finally:
            page = response.meta['playwright_page']    
            await page.context.close()
            await page.close()
    
    def start_requests(self):
        request = self._build_request(self.url)
        yield request
    
    def _build_request(self, url):
        request = scrapy.Request(url = url, 
                callback=self.parse_response,
                errback= self.close_context_on_error,
                meta = {"playwright": True, 
                        "playwright_context": uuid.uuid4(),
                        "playwright_include_page": True,
                        }
                )

        return request

    async def close_context_on_error(self, failure):
        if "playwright_page" in failure.request.meta: # "playwright_page" is not included if request is blocked because of robots.txt
            page = failure.request.meta["playwright_page"]
            await page.context.close()
            await page.close()
```

I don't think brower/context error are impacting me much but would like get rid of annoying errors in the log. Any idea about the approach to close the context and page and not get the "context/page closed errors"

As an additional note, I thought of implementing the solution to close the context after say 100 requests but it turned it is not easy to implement in Spider class. It will be really useful feature to implement in handler to close and context after configured number of requests are handled by it. Until then please write some notes in the readme file about memory issue.

Thanks for writing this handler. It is quite useful.

**Comment by elacuesta** [comment]
Sorry, I'm not able to reproduce. Here's an adapted version of your spider, filling the blanks to scrape books.toscrape.com and visit all pages, which runs fine without any exceptions:
```python
import uuid
import scrapy

class TestSpider(scrapy.Spider):
    name = "test_all"
    custom_settings = {
        "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
        "DOWNLOAD_HANDLERS": {
            "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
        },
    }

    def start_requests(self):
        yield self._build_request("http://books.toscrape.com")

    async def parse(self, response):
        yield {"url": response.url}
        for child_link in response.css("a::attr(href)").getall():
            yield self._build_request(response.urljoin(child_link))
        page = response.meta["playwright_page"]
        await page.context.close()
        await page.close()

    async def close_context_on_error(self, failure):
        if "playwright_page" in failure.request.meta:
            page = failure.request.meta["playwright_page"]
            await page.context.close()
            await page.close()

    def _build_request(self, url):
        return scrapy.Request(
            url=url,
            errback=self.close_context_on_error,
            meta={
                "playwright": True,
                "playwright_context": uuid.uuid4(),
                "playwright_include_page": True,
            },
        )
```

<details>
  <summary>Full crawl logs</summary>

  ```
  scrapy runspider examples/test_all.py -o book_urls.json -s LOG_LEVEL=INFO
2022-10-11 16:24:51 [scrapy.utils.log] INFO: Scrapy 2.6.0 started (bot: scrapybot)
2022-10-11 16:24:51 [scrapy.utils.log] INFO: Versions: lxml 4.8.0.0, libxml2 2.9.12, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 22.2.0, Python 3.9.6 (default, Sep  6 2021, 10:09:19) - [GCC 7.5.0], pyOpenSSL 22.0.0 (OpenSSL 1.1.1m  14 Dec 2021), cryptography 36.0.1, Platform Linux-5.4.0-125-generic-x86_64-with-glibc2.31
2022-10-11 16:24:51 [scrapy.crawler] INFO: Overridden settings:
{'EDITOR': 'nano',
 'LOG_LEVEL': 'INFO',
 'SPIDER_LOADER_WARN_ONLY': True,
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'}
2022-10-11 16:24:51 [scrapy.extensions.telnet] INFO: Telnet Password: 28232af77a14f160
2022-10-11 16:24:51 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2022-10-11 16:24:51 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2022-10-11 16:24:51 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2022-10-11 16:24:51 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2022-10-11 16:24:51 [scrapy.core.engine] INFO: Spider opened
2022-10-11 16:24:51 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2022-10-11 16:24:51 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2022-10-11 16:24:51 [scrapy-playwright] INFO: Starting download handler
2022-10-11 16:24:56 [scrapy-playwright] INFO: Launching browser chromium
2022-10-11 16:24:56 [scrapy-playwright] INFO: Browser chromium launched
2022-10-11 16:25:51 [scrapy.extensions.logstats] INFO: Crawled 103 pages (at 103 pages/min), scraped 101 items (at 101 items/min)
2022-10-11 16:26:51 [scrapy.extensions.logstats] INFO: Crawled 213 pages (at 110 pages/min), scraped 213 items (at 112 items/min)
2022-10-11 16:27:51 [scrapy.extensions.logstats] INFO: Crawled 335 pages (at 122 pages/min), scraped 334 items (at 121 items/min)
2022-10-11 16:28:51 [scrapy.extensions.logstats] INFO: Crawled 462 pages (at 127 pages/min), scraped 461 items (at 127 items/min)
2022-10-11 16:29:51 [scrapy.extensions.logstats] INFO: Crawled 590 pages (at 128 pages/min), scraped 590 items (at 129 items/min)
2022-10-11 16:30:51 [scrapy.extensions.logstats] INFO: Crawled 719 pages (at 129 pages/min), scraped 718 items (at 128 items/min)
2022-10-11 16:31:51 [scrapy.extensions.logstats] INFO: Crawled 845 pages (at 126 pages/min), scraped 844 items (at 126 items/min)
2022-10-11 16:32:51 [scrapy.extensions.logstats] INFO: Crawled 973 pages (at 128 pages/min), scraped 973 items (at 129 items/min)
2022-10-11 16:33:51 [scrapy.extensions.logstats] INFO: Crawled 1100 pages (at 127 pages/min), scraped 1098 items (at 125 items/min)
2022-10-11 16:34:51 [scrapy.extensions.logstats] INFO: Crawled 1165 pages (at 65 pages/min), scraped 1165 items (at 67 items/min)
2022-10-11 16:35:51 [scrapy.extensions.logstats] INFO: Crawled 1191 pages (at 26 pages/min), scraped 1191 items (at 26 items/min)
2022-10-11 16:35:58 [scrapy.core.engine] INFO: Closing spider (finished)
2022-10-11 16:35:58 [scrapy.extensions.feedexport] INFO: Stored json feed (1195 items) in: book_urls.json
2022-10-11 16:35:58 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 424006,
 'downloader/request_count': 1195,
 'downloader/request_method_count/GET': 1195,
 'downloader/response_bytes': 28275026,
 'downloader/response_count': 1195,
 'downloader/response_status_count/200': 1195,
 'dupefilter/filtered': 32062,
 'elapsed_time_seconds': 667.40722,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2022, 10, 11, 19, 35, 58, 898921),
 'item_scraped_count': 1195,
 'log_count/INFO': 25,
 'memusage/max': 133840896,
 'memusage/startup': 63234048,
 'playwright/context_count': 1195,
 'playwright/context_count/max_concurrent': 11,
 'playwright/context_count/non-persistent': 1195,
 'playwright/page_count': 1195,
 'playwright/page_count/max_concurrent': 11,
 'playwright/request_count': 22229,
 'playwright/request_count/method/GET': 22229,
 'playwright/request_count/navigation': 1195,
 'playwright/request_count/resource_type/document': 1195,
 'playwright/request_count/resource_type/font': 1195,
 'playwright/request_count/resource_type/image': 10279,
 'playwright/request_count/resource_type/script': 5975,
 'playwright/request_count/resource_type/stylesheet': 3585,
 'playwright/response_count': 22229,
 'playwright/response_count/method/GET': 22229,
 'playwright/response_count/resource_type/document': 1195,
 'playwright/response_count/resource_type/font': 1195,
 'playwright/response_count/resource_type/image': 10279,
 'playwright/response_count/resource_type/script': 5975,
 'playwright/response_count/resource_type/stylesheet': 3585,
 'request_depth_max': 51,
 'response_received_count': 1195,
 'scheduler/dequeued': 1195,
 'scheduler/dequeued/memory': 1195,
 'scheduler/enqueued': 1195,
 'scheduler/enqueued/memory': 1195,
 'start_time': datetime.datetime(2022, 10, 11, 19, 24, 51, 491701)}
2022-10-11 16:35:58 [scrapy.core.engine] INFO: Spider closed (finished)
2022-10-11 16:35:58 [scrapy-playwright] INFO: Closing download handler
2022-10-11 16:35:58 [scrapy-playwright] INFO: Closing browser
  ```
</details>

At first I suspected it could be a problem with awaiting `context.close()` followed by `page.close()` because AFAIK closing the context also closes its pages, but it seems like that's not really an issue (at least in my limited test). Just to be 100% sure though, could you swap the order of those calls, or even remove the `await page.close()` call?

In my test I did not modify any of the concurrency defaults, and the handler only reached 11 concurrent contexts, 1195 in total.
What's your environment and concurrency settings?

**Comment by gurmitteotia** [comment]
Swapping the order of close sequence (closing page first then context) has resolved the issue for me. I'm no more getting these error. Thank you for the help.

I'm wondering why you're not able reproduce this issue?

Here is additional information:
OS- Debian 11
playwright==1.25.2
scrapy = 2.6.3
scrapy-playwright=0.0.21

Concurrency settings:
CONCURRENT_REQUESTS = 4
CONCURRENT_REQUESTS_PER_DOMAIN = 4
Rest of concurrency settings are default.

**Comment by gurmitteotia** [comment]
Closing the issue as swapping the close order of context and page solved the issue for me. However it will be useful to add a note in readme about playwright not releasing the memory and the workaround.

**Comment by Gidgidonihah** [comment]
It would indeed be helpful to have a note about this in the readme. I ran into the same issue, did some debugging, then found this *closed* issue.

It seems very heavy-handed to have to create a new context for every page, but as noted, seems like that's a problem with playwright itself. I'll open a new ticket to request a note about this in the readme. 

For reference, I'll go ahead and post my debugging info here:

I assumed it must be something to do with my code, so I stripped it down to a MRE, with basically none of my code and the memory leak remained.

I used `mprof` to profile and plot memory usage over the lifetime of the crawl. The only difference between runs was if these lines were commented out in `_get_request` (see example code below):
```py
"playwright": True,
"playwright_include_page": True,
```

With the first run, the control if you will, with both lines commented out, not using playwright at all.
![books](https://user-images.githubusercontent.com/91488/224780502-6c3ce9e6-c68e-4d04-8bc8-2e30401fd472.png)

Next I uncommented both lines using playwright to render each page *and* returning the page to be closed by the parse method:
![books-pw](https://user-images.githubusercontent.com/91488/224780176-dd4d70e4-ec1c-4f49-b477-7d6a45c2b76e.png)

A clearly linear progression of memory usage.

Then I wondered if it might have something to do with including the page, so I ran still rendering with playwright, but without the page included. Same linear results:
![books-pw-no-page](https://user-images.githubusercontent.com/91488/224780807-c7771de5-e619-49f9-a78b-4da9a6d94587.png)

I crawled books.toscrape.com capping out at a max 500 pages. Obviously, if I don't cap the page limit, the linear growth continues.

Of note, when crawling a different site with heavier pages, the crawls took longer (8 mins, vs 2 mins) and resulted in much higher memory usage. Also capped at 500 pages:
![fresh-basic-500-pw](https://user-images.githubusercontent.com/91488/224781540-8b74f29a-5ec5-4d30-9b51-494fea2946e6.png)

Then I played with contexts for a bit. I discovered that if I create a new context for every page `'playwright_context': uuid.uuid4(),` and then close the context after I close the page (`await page.context.close()`) the memory usage is a lot more reasonable. However this seems like a pretty heavy-handed approach.
![books-xcontext](https://user-images.githubusercontent.com/91488/224784737-d69e59cf-f36b-4822-8e51-b04077a4b159.png)

And that is exactly what was landed on in this issue, before I came across it. My mistake for glossing over since it was closed.


Example code:
```py
from scrapy import Request
from scrapy import Spider
from scrapy.http.response import Response
from scrapy.linkextractors import LinkExtractor


class BasicSpider(Spider):
    """Test."""

    custom_settings = {
        "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
        "DOWNLOAD_HANDLERS": {
            "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
            "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
        },
        "CONCURRENT_REQUESTS": 32,
        "PLAYWRIGHT_MAX_PAGES_PER_CONTEXT": 4,
        "CLOSESPIDER_PAGECOUNT": 500,
    }

    name = "basic"
    start_urls = ["https://books.toscrape.com"]
    allowed_domains = ["books.toscrape.com"]

    def __init__(self, name=None, **kwargs):
        super().__init__(name, **kwargs)
        self.link_extractor = LinkExtractor()

    def parse(self, response: Response, **kwargs):
        """Parse the first page."""
        for link in self.link_extractor.extract_links(response):
            yield self._get_request(link.url)

    async def _parse_page(self, response: Response):
        page = response.meta.get("playwright_page")
        if page:
            await page.close()

        for link in self.link_extractor.extract_links(response):
            yield self._get_request(link.url)

    def _get_request(self, url):
        return Request(
            url,
            callback=self._parse_page,
            meta={
                # "playwright": True,
                # "playwright_include_page": True,
            },
            errback=self.errback_close_page,
        )

    async def errback_close_page(self, failure):
        """Close the page."""
        page = failure.request.meta.get("playwright_page")
        if page:
            await page.close()
```
