### ISSUE TITLE
Recursively send same requests with spider opened

### ISSUE THREAD

**Issue by lime-n** [scrapy-plugins/scrapy-playwright#132]
I am practicing with my spider to produce an indefinite number of requests sent to the spider. These will all each open up a new page; and when the handler is finished as opposed to when the crawl is done, then close the page and its context. Then recursively repeat this.

Reproducible code:
```python
from datetime import datetime
import scrapy
from playwright.async_api import Response as PlaywrightResponse
from scrapy_playwright.page import PageMethod
import jsonlines
from scrapy import signals

headers = {
    'Accept': 'application/json; charset=UTF-8',
    'Content-Type': 'application/json; charset=UTF-8',
    'Origin': 'https://betway.com',
    'Accept-Language': 'en-GB,en;q=0.9',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15',
    'Referer': 'https://betway.com/',
    'Connection': 'keep-alive',
}

class OddsSpider(scrapy.Spider):
    yet = False
    name = 'oddsB'
    start_urls = ['https://betway.com/en/sports/grp/soccer/european-cups/uefa-champions-league']

    custom_settings = {
        'DOWNLOAD_DELAY': 3
    }

    def start_requests(self):
        yield scrapy.FormRequest(
                url=self.start_urls[0],
                headers=headers,
                dont_filter = True,
                callback = self.parse_in_new_context, 
                errback = self.close_context_on_error,
                meta = dict(
                    playwright = True,
                    playwright_include_page = True,
                    playwright_page_methods = [
                    PageMethod('wait_for_selector', selector = '.layout.firstRowContainer.collection.horizontal', state = 'visible'),
                    ],
                    playwright_page_event_handlers={
                    "response": "handle_response",
                }
                    ))

    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs):
        spider = super(OddsSpider, cls).from_crawler(crawler, *args, **kwargs)
        crawler.signals.connect(spider.spider_idle, signal=signals.spider_idle)
        return spider

    def spider_idle(self, spider):
        if not self.yet:
            aRequest = scrapy.FormRequest(
                url=self.start_urls[0],
                headers=headers,
                dont_filter = True,
                callback = self.parse_in_new_context, 
                errback = self.close_context_on_error,
                meta = dict(
                    playwright = True,
                    playwright_include_page = True,
                    playwright_page_methods = [
                    PageMethod('wait_for_selector', selector = '.eventTableItemCollection', state = 'visible'),
                    #PageMethod("screenshot", path=Path(__file__).parent / "betway2.png", full_page=True)
                    ],
                    playwright_page_event_handlers={
                    "response": "handle_response",
                }
                    ))
            spider.crawler.engine.crawl(aRequest)

    def handle_response(self, response: PlaywrightResponse)  -> None:
        self.logger.info(f'test the log of data: {response.request.resource_type, response.request.url, response.request.method}')
        jl_file = "GetEvents.jl"
        data = {}
        if response.request.resource_type == "xhr":
            if response.request.method == "POST":
                if 'GetEvents' in response.request.url:
                    data['resource_type']=response.request.resource_type,
                    data['request_url']=response.request.url,
                    data['post_data']=response.request.post_data_json,
                    data['method']=response.request.method
                    data['time']=datetime.now().strftime("%d/%m/%Y %H:%M:%S")
                    with jsonlines.open(jl_file, mode='a') as writer:
                        writer.write(data)
    
    async def parse_in_new_context(self, response):
        page = response.meta["playwright_page"]
        await page.context.close()  # close the context
        await page.close()

    
    async def close_context_on_error(self, failure):
        page = failure.request.meta["playwright_page"]
        await page.context.close()
```

I get this peculiar error and wanted to know whether the pages are being closed properly and whether I am wasting memory by not closing them properly?
```
2022-10-14 20:30:26 [asyncio] ERROR: Exception in callback AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...been closed')>) at /Users/usr/bettingOdds/venv/lib/python3.8/site-packages/pyee/_asyncio.py:55
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>._callback(<Task finishe...been closed')>) at /Users/usr/bettingOdds/venv/lib/python3.8/site-packages/pyee/_asyncio.py:55>
Traceback (most recent call last):
  File "/Users/usr/opt/anaconda3/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/usr/bettingOdds/venv/lib/python3.8/site-packages/pyee/_asyncio.py", line 62, in _callback
    self.emit('error', exc)
  File "/Users/usr/bettingOdds/venv/lib/python3.8/site-packages/pyee/_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/Users/usr/bettingOdds/venv/lib/python3.8/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "/Users/usr/bettingOdds/venv/lib/python3.8/site-packages/scrapy_playwright/handler.py", line 453, in _log_request
    referrer = await response.header_value("referer")
  File "/Users/usr/bettingOdds/venv/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 503, in header_value
    return mapping.from_maybe_impl(await self._impl_obj.header_value(name=name))
  File "/Users/usr/bettingOdds/venv/lib/python3.8/site-packages/playwright/_impl/_network.py", line 461, in header_value
    return (await self._actual_headers()).get(name)
  File "/Users/usr/bettingOdds/venv/lib/python3.8/site-packages/playwright/_impl/_network.py", line 469, in _actual_headers
    headers = cast(HeadersArray, await self._channel.send("rawResponseHeaders"))
  File "/Users/usr/bettingOdds/venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/Users/usr/bettingOdds/venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 396, in wrap_api_call
    return await cb()
  File "/Users/usr/bettingOdds/venv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
```

**Comment by elacuesta** [comment]
I'm not that familiar with Playwright's internals so I might be wrong, but it looks like the task that sends the `response` event hasn't finished by the time you close the page/context (see the failing task is `AsyncIOEventEmitter._emit_run`).
I don't think this is a safe pattern, perhaps you could add some [locking](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Lock) to prevent the page/context from being closed before the response handler finishes.

**Comment by lime-n** [comment]
@elacuesta having only `await page.close()` inside `parse_in_new_context` prevents the error from occurring however we do not close the context, would this pose long-term issues?

**Comment by elacuesta** [comment]
Upon closer inspection, I don't see any occurrences of the `playwright_context` request meta key, meaning all requests are downloaded with the same context ("default"): it makes sense that it fails if you close the context but doesn't if you only close the pages. In this case then it's not necessary to pass `playwright_include_page=True` and manually close the pages in the callback, the handler does it automatically (as explained in the readme).

However, it had been [reported upstream](https://github.com/microsoft/playwright/issues/6319) that having long-lived contexts can lead to memory issues.

**Comment by lime-n** [comment]
I'll have to look into this some further when I have more spare time. I believe I partially cleaned up this issue by removing `await page.context.close()`
