### ISSUE TITLE
AttributeError: Can't pickle local object 'Page.__init__.<locals>.<lambda>'

### ISSUE THREAD

**Issue by LLLLLLLHHHHH** [scrapy-plugins/scrapy-playwright#153]
crawl url: "https://219.142.91.6/"
Traceback (most recent call last):
  File "/Users/Anaconda/anaconda3/envs/fofa/lib/python3.8/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/Users/Anaconda/anaconda3/envs/fofa/lib/python3.8/site-packages/scrapy/core/engine.py", line 206, in _handle_downloader_output
    self.crawl(result)
  File "/Users/Anaconda/anaconda3/envs/fofa/lib/python3.8/site-packages/scrapy/core/engine.py", line 250, in crawl
    self._schedule_request(request, self.spider)
  File "/Users/Anaconda/anaconda3/envs/fofa/lib/python3.8/site-packages/scrapy/core/engine.py", line 255, in _schedule_request
    if not self.slot.scheduler.enqueue_request(request):  # type: ignore[union-attr]
  File "/Users/Anaconda/anaconda3/envs/fofa/lib/python3.8/site-packages/scrapy_redis/scheduler.py", line 158, in enqueue_request
    self.queue.push(request)
  File "/Users/Anaconda/anaconda3/envs/fofa/lib/python3.8/site-packages/scrapy_redis/queue.py", line 103, in push
    data = self._encode_request(request)
  File "/Users/Anaconda/anaconda3/envs/fofa/lib/python3.8/site-packages/scrapy_redis/queue.py", line 47, in _encode_request
    return self.serializer.dumps(obj)
  File "/Users/Anaconda/anaconda3/envs/fofa/lib/python3.8/site-packages/scrapy_redis/picklecompat.py", line 14, in dumps
    return pickle.dumps(obj, protocol=-1)
AttributeError: Can't pickle local object 'Page.__init__.<locals>.<lambda>'

**Comment by Gallaecio** [comment]
Can you provide a minimal, reproducible example?

**Comment by Laerte** [comment]
@Gallaecio @elacuesta can we close this one?

**Comment by Gallaecio** [comment]
Yes. Thanks, @Laerte!
