### ISSUE TITLE
Issues with using Scrapy Scrapy-playwright

### ISSUE THREAD

**Issue by whiteleodarkseid** [scrapy-plugins/scrapy-playwright#154]
I am sorry if this is an issue that has already been solved;I am new to using scrapy, but I keep on getting this error when I run `Scrapy crawl pwdemo`

```
[asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\_impl\_connection.py:240> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\_impl\_transport.py", line 132, in connect
    raise exc
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 218, in create_subprocess_exec       
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1680, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport  
    raise NotImplementedError
NotImplementedError
2023-01-12 14:08:47 [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-4' coro=<Connection.run() done, defined at C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\_impl\_connection.py:240> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\_impl\_connection.py", line 247, in run
    await self._transport.connect()
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\_impl\_transport.py", line 132, in connect
    raise exc
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 218, in create_subprocess_exec       
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1680, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport  
    raise NotImplementedError
NotImplementedError
2023-01-12 14:08:47 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ScrapyPlaywrightDownloadHandler._engine_started of <scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler object at 0x0000014CD25C7710>>
Traceback (most recent call last):
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\scrapy_playwright\handler.py", line 116, in _launch
    self.playwright = await self.playwright_context_manager.start()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 218, in create_subprocess_exec       
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1680, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport  
    raise NotImplementedError
NotImplementedError
2023-01-12 14:08:47 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ScrapyPlaywrightDownloadHandler._engine_started of <scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler object at 0x0000014CD2870AD0>>
Traceback (most recent call last):
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\scrapy_playwright\handler.py", line 116, in _launch
    self.playwright = await self.playwright_context_manager.start()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 218, in create_subprocess_exec       
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1680, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport  
    raise NotImplementedError
NotImplementedError
2023-01-12 14:09:05 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://shoppable-campaign-demo.netlify.app/robots.txt> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
ERROR: Error downloading <GET https://shoppable-campaign-demo.netlify.app/#/>
Traceback (most recent call last):
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\twisted\internet\defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\twisted\python\failure.py", line 518, in throwExceptionIntoGenerator      
    return g.throw(self.type, self.value, self.tb)
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\scrapy\core\downloader\middleware.py", line 49, in process_request        
    return (yield download_func(request=request, spider=spider))
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\scrapy_playwright\handler.py", line 248, in _download_request
    page = await self._create_page(request)
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\scrapy_playwright\handler.py", line 174, in _create_page
    context = await self._create_browser_context(
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\scrapy_playwright\handler.py", line 149, in _create_browser_context       
    await self._maybe_launch_browser()
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\scrapy_playwright\handler.py", line 133, in _maybe_launch_browser
    logger.info("Launching browser %s", self.browser_type.name)
AttributeError: 'ScrapyPlaywrightDownloadHandler' object has no attribute 'browser_type'
2023-01-12 14:09:06 [scrapy.core.engine] INFO: Closing spider (finished)
2023-01-12 14:09:06 [scrapy.statscollectors] INFO: Dumping Scrapy stats:

2023-01-12 14:09:06 [scrapy-playwright] INFO: Closing download handler
2023-01-12 14:09:06 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method DownloadHandlers._close of <scrapy.core.downloader.handlers.DownloadHandlers object at 0x0000014CD255AED0>>
Traceback (most recent call last):
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\twisted\internet\defer.py", line 1693, in _inlineCallbacks
    result = context.run(
             ^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\twisted\python\failure.py", line 518, in throwExceptionIntoGenerator      
    return g.throw(self.type, self.value, self.tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 81, in _close
    yield dh.close()
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\twisted\internet\defer.py", line 1693, in _inlineCallbacks
    result = context.run(
             ^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\twisted\python\failure.py", line 518, in throwExceptionIntoGenerator      
    return g.throw(self.type, self.value, self.tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\scrapy_playwright\handler.py", line 230, in close
    yield deferred_from_coro(self._close())
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\scrapy_playwright\handler.py", line 238, in _close
    await self.playwright_context_manager.__aexit__()
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\async_api\_context_manager.py", line 54, in __aexit__
    await self._connection.stop_async()
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\_impl\_connection.py", line 258, in stop_async
    self._transport.request_stop()
  File "C:\Users\kolad\Desktop\last\last\Lib\site-packages\playwright\_impl\_transport.py", line 101, in request_stop
    assert self._output
           ^^^^^^^^^^^^
AttributeError: 'PipeTransport' object has no attribute '_output'
```

I expected for it to run the website and return my selected items, but instead I get the error above, I have all dependencies installed in my venv, and I have also ran playwright.install  thus I have the browsers

Help would be appreciated

**Comment by elacuesta** [comment]
scrapy-playwright does not run natively on Windows, see the notes in the readme: https://github.com/scrapy-plugins/scrapy-playwright#lack-of-native-support-for-windows

**Comment by whiteleodarkseid** [comment]
Oh, thanks

**Comment by whiteleodarkseid** [comment]
Oh, thanks
