### ISSUE TITLE
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded - (Headless: True)

### ISSUE THREAD

**Issue by mostafa6765** [scrapy-plugins/scrapy-playwright#204]
I am facing a timeout issue when setting headless true. with `Headless: False` working fine.

# Issue
```bash
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("jb-flight-detail-item") to be visible
============================================================
```
# setting 
```python
REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
FEED_EXPORT_ENCODING = "utf-8"


PLAYWRIGHT_LAUNCH_OPTIONS = {"headless": True}
PLAYWRIGHT_BROWSER_TYPE = "chromium"
PLAYWRIGHT_DEFAULT_NAVIGATION_TIMEOUT = 40 * 1000

DOWNLOAD_HANDLERS = {
    "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
    "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
}
```

# spider
```python
import scrapy
from scrapy_playwright.page import PageMethod

class JetblueSpider(scrapy.Spider):
    name = 'jetbluespider'

    def start_requests(self):
        depart_date = getattr(self,'depart_date','2023-07-16')
        depart_from = getattr(self,'depart_from','JFK')
        arrival_to = getattr(self,'arrival_to','DFW')
        print(f'depart_date {depart_date}')
        print(f'from {depart_from}')
        print(f'to {arrival_to}')
        
        yield scrapy.Request(
            url=f"https://www.jetblue.com/booking/flights?from={depart_from}&to={arrival_to}&depart={depart_date}&return=2023-08-27&isMultiCity=false&noOfRoute=1&lang=en&adults=1&children=0&infants=0&sharedMarket=false&roundTripFaresFlag=false&usePoints=true",
            meta={
                "playwright": True,
                "playwright_include_page": True,
                "playwright_page_methods": [
                    PageMethod("wait_for_selector", 'jb-flight-detail-item'),
                ]
            },
        )

    async def parse(self, response):
        # playwright instance.
        # page = response.meta["playwright_page"]
        # await page.wait_for_timeout(3000)
        
        flights = response.css('.w-100.lh-copy.flex.relative.flex-wrap.css-for-itineraries.pv4.ph3.pa4-ns.pb3-ns')

        for index, flight in enumerate(flights):
                        
            # points selector.
            points = flight.css('.w-100.relative.fareCardWithPointsContainer.topMargin.ng-star-inserted')
            
            # Here we put the data returned into the format we want to output for our csv or json file
            yield {
                'index': index,
                'depart_time': flight.css(f'#auto-depart-time-{index}::text').get(),
            }
            
         ```

**Comment by elacuesta** [comment]
I'm seeing the same result with standalone Playwright:

```python
# gh204.py
import asyncio
from playwright.async_api import async_playwright

depart_date = "2023-07-16"
depart_from = "JFK"
arrival_to = "DFW"

async def main():
    async with async_playwright() as pw:
        print(f"depart_date {depart_date}")
        print(f"from {depart_from}")
        print(f"to {arrival_to}")
        browser = await pw.chromium.launch(headless=True)
        page = await browser.new_page()
        page.set_default_navigation_timeout(40 * 1000)
        await page.goto(url=...)
        await page.wait_for_selector("jb-flight-detail-item")
        await page.screenshot(path="flight-detail.png", full_page=True)
        await browser.close()

asyncio.run(main())
```

```
$ $ python gh204.py
depart_date 2023-07-16
from JFK
to DFW
Traceback (most recent call last):
  File "/Users/eus/scrapy-playwright/gh204.py", line 26, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/eus/scrapy-playwright/examples/gh204.py", line 21, in main
    await page.wait_for_selector("jb-flight-detail-item")
  File "/Users/eus/scrapy-playwright/venv-scrapy-playwright/lib/python3.9/site-packages/playwright/async_api/_generated.py", line 8301, in wait_for_selector
    await self._impl_obj.wait_for_selector(
  File "/Users/eus/scrapy-playwright/venv-scrapy-playwright/lib/python3.9/site-packages/playwright/_impl/_page.py", line 352, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "/Users/eus/scrapy-playwright/venv-scrapy-playwright/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 322, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/Users/eus/scrapy-playwright/venv-scrapy-playwright/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/Users/eus/scrapy-playwright/venv-scrapy-playwright/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/Users/eus/scrapy-playwright/venv-scrapy-playwright/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("jb-flight-detail-item") to be visible
============================================================
```

For reference, this is using `playwright==1.35.0` & `scrapy==2.9.0`.

That means it's not caused by this integration. If you need to report an issue I'd suggest you do it upstream as [mentioned in the docs](https://github.com/scrapy-plugins/scrapy-playwright#reporting-issues).
