### ISSUE TITLE
Unable to render a page with a meta refresh tag

### ISSUE THREAD

**Issue by Gidgidonihah** [scrapy-plugins/scrapy-playwright#217]
If I try to render a page that has an immediate meta refresh tag, scrapy_playwright will always raise:

> playwright._impl._api_types.Error: Unable to retrieve content because the page is navigating and changing the content.

I've put together a [minimum reproducible example](https://github.com/Gidgidonihah/mre-for-scrapy-playwright-meta-refresh). 

All it takes is a basic spider trying to render a page with the following content:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Page should redirect</title>
    <link rel="canonical" href="result.html">
    <meta name="robots" content="noindex">
    <meta charset="utf-8">
    <meta http-equiv="refresh" content="0; url=result.html">
  </head>
</html>
```

The following error will be raised:
```
ERROR: Error downloading <GET https://gidgidonihah.github.io/mre-for-scrapy-playwright-meta-refresh/>
Traceback (most recent call last):
  File "/virtualenvs/mre/lib/python3.10/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "/virtualenvs/mre/lib/python3.10/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/virtualenvs/mre/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 54, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/virtualenvs/mre/lib/python3.10/site-packages/twisted/internet/defer.py", line 1065, in adapt
    extracted = result.result()
  File "/virtualenvs/mre/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 301, in _download_request
    result = await self._download_request_with_page(request, page, spider)
  File "/virtualenvs/mre/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 354, in _download_request_with_page
    body_str = await page.content()
  File "/virtualenvs/mre/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 9146, in content
    return mapping.from_maybe_impl(await self._impl_obj.content())
  File "/virtualenvs/mre/lib/python3.10/site-packages/playwright/_impl/_page.py", line 462, in content
    return await self._main_frame.content()
  File "/virtualenvs/mre/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 415, in content
    return await self._channel.send("content")
  File "/virtualenvs/mre/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/virtualenvs/mre/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/virtualenvs/mre/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Unable to retrieve content because the page is navigating and changing the content.
```

The key is that [line 354 of handler.py](https://github.com/scrapy-plugins/scrapy-playwright/blob/8a73cf37598f4f20fb298b2763a6a5ea87bceb5b/scrapy_playwright/handler.py#L354) calls `page.content()`, which, because the page is indeed navigating, playwright raises an error.

The [related bug on playwright](https://github.com/microsoft/playwright/issues/20483) is closed and recommends retrying the `page.content()` call. See also https://github.com/scrapy-plugins/scrapy-playwright/issues/186

**Comment by elacuesta** [comment]
Thanks for the thorough investigation and the reproducible example. For the record, this doesn't seem to be an issue for firefox & webkit.
