### ISSUE TITLE
NotImplementedError as well as other errors when simply executing spider

### ISSUE THREAD

**Issue by emilrueh** [scrapy-plugins/scrapy-playwright#235]
## Where am I?
Just installed scrapy-playwright and set all my settings, created a spider using the meta + PageMethods wait_for_selector.

- Python 3.11.2
- Scrapy 2.11.0
- Scrapy-playwright 0.0.32
- Playwright 1.38.0

## What happened?
I get an immediate error log raising multiple errors but mainly the `NotImplementedError` and it seems to be pointing towards asyncio.
Also the error `AttributeError: 'PipeTransport' object has no attribute '_output'` shows at the bottom of the log.

### Info:
Below I showcase my `settings.py`, as well as my spider's `start_request()` function, and the full error log I get.
I tried deleting the `async` infront of `def parse()` with no result.

# Question:
**Is this a bug or simply a missing install on my end or perhaps a versioning issue?**

---
#### settings.py
```python
BOT_NAME = "mine"
SPIDER_MODULES = ["mine.spiders"]
NEWSPIDER_MODULE = "mine.spiders"
DOWNLOAD_HANDLERS = {
    "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
    "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
}
ROBOTSTXT_OBEY = True
REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
FEED_EXPORT_ENCODING = "utf-8"

```

#### spider
```python
    def start_requests(self):
        yield Request(
            url=self.base_url,
            cookies=self.cookies,
            callback=self.callback,
            meta=dict(
                playwright=True,
                playwright_inclue_page=True,
                playwright_page_methods=[PageMethod("wait_for_selector", "div#bProducts")],
            ),
        )

    async def parse(self, response):
```
---
#### full error log
```powershell
(venv) PS C:\Users\user\data_mine\mine> scrapy crawl laptops -O laptops_js.json     
2023-09-22 21:12:44 [scrapy.utils.log] INFO: Scrapy 2.11.0 started (bot: mine)
2023-09-22 21:12:44 [scrapy.utils.log] INFO: Versions: lxml 4.9.3.0, libxml2 2.10.3, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 22.10.0, Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)], pyOpenSSL 23.2.0 (OpenSSL 3.1.2 1 Aug 2023), cryptography 41.0.3, Platform Windows-10-10.0.19045-SP0       
2023-09-22 21:12:44 [scrapy.addons] INFO: Enabled addons:
[]
2023-09-22 21:12:44 [asyncio] DEBUG: Using selector: SelectSelector
2023-09-22 21:12:44 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.asyncioreactor.AsyncioSelectorReactor
2023-09-22 21:12:44 [scrapy.utils.log] DEBUG: Using asyncio event loop: asyncio.windows_events._WindowsSelectorEventLoop
2023-09-22 21:12:44 [scrapy.extensions.telnet] INFO: Telnet Password: da289763840e350f
2023-09-22 21:12:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2023-09-22 21:12:44 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'mine',
 'FEED_EXPORT_ENCODING': 'utf-8',
 'NEWSPIDER_MODULE': 'mine.spiders',
 'REQUEST_FINGERPRINTER_IMPLEMENTATION': '2.7',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['mine.spiders'],
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'}
2023-09-22 21:12:45 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2023-09-22 21:12:45 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2023-09-22 21:12:45 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2023-09-22 21:12:45 [scrapy.core.engine] INFO: Spider opened
2023-09-22 21:12:45 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2023-09-22 21:12:45 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6024
2023-09-22 21:12:45 [scrapy-playwright] INFO: Starting download handler
2023-09-22 21:12:45 [scrapy-playwright] INFO: Starting download handler
2023-09-22 21:12:45 [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\_impl\_connection.py:264> exception=NotImplementedError()>     
Traceback (most recent call last):
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\_impl\_connection.py", line 271, in run
    await self._transport.connect()
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\_impl\_transport.py", line 135, in connect
    raise exc
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\_impl\_transport.py", line 123, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2023-09-22 21:12:45 [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-4' coro=<Connection.run() done, defined at C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\_impl\_connection.py:264> exception=NotImplementedError()>     
Traceback (most recent call last):
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\_impl\_connection.py", line 271, in run
    await self._transport.connect()
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\_impl\_transport.py", line 135, in connect
    raise exc
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\_impl\_transport.py", line 123, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2023-09-22 21:12:45 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ScrapyPlaywrightDownloadHandler._engine_started of <scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler object at 0x00000251E70B8950>>
Traceback (most recent call last):
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\scrapy_playwright\handler.py", line 126, in _launch
    self.playwright = await self.playwright_context_manager.start()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\async_api\_context_manager.py", line 52, in start
    return await self.__aenter__()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\async_api\_context_manager.py", line 47, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\_impl\_transport.py", line 123, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2023-09-22 21:12:45 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ScrapyPlaywrightDownloadHandler._engine_started of <scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler object at 0x00000251E70E3FD0>>
Traceback (most recent call last):
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\scrapy_playwright\handler.py", line 126, in _launch
    self.playwright = await self.playwright_context_manager.start()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\async_api\_context_manager.py", line 52, in start
    return await self.__aenter__()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\async_api\_context_manager.py", line 47, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\_impl\_transport.py", line 123, in connect
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2023-09-22 21:12:50 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.mindfactory.de/robots.txt> (referer: None)
2023-09-22 21:12:50 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.mindfactory.de/Notebook+~+PC/Notebooks.html>
Traceback (most recent call last):
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\twisted\internet\defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\twisted\python\failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\scrapy\core\downloader\middleware.py", line 54, in process_request
    return (yield download_func(request=request, spider=spider))
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\scrapy_playwright\handler.py", line 296, in _download_request
    page = await self._create_page(request=request, spider=spider)
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\scrapy_playwright\handler.py", line 220, in _create_page
    ctx_wrapper = await self._create_browser_context(
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\scrapy_playwright\handler.py", line 179, in _create_browser_context
    await self._maybe_launch_browser()
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\scrapy_playwright\handler.py", line 144, in _maybe_launch_browser
    logger.info("Launching browser %s", self.browser_type.name)
AttributeError: 'ScrapyPlaywrightDownloadHandler' object has no attribute 'browser_type'
2023-09-22 21:12:50 [scrapy.core.engine] INFO: Closing spider (finished)
2023-09-22 21:12:50 [scrapy.extensions.feedexport] INFO: Stored json feed (0 items) in: laptops_js.json
2023-09-22 21:12:50 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/builtins.AttributeError': 1,
 'downloader/request_bytes': 523,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 1086,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 5.403303,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 9, 22, 19, 12, 50, 611320, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 2118,
 'httpcompression/response_count': 1,
 'log_count/DEBUG': 4,
 'log_count/ERROR': 5,
 'log_count/INFO': 13,
 'response_received_count': 1,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2023, 9, 22, 19, 12, 45, 208017, tzinfo=datetime.timezone.utc)}
2023-09-22 21:12:50 [scrapy.core.engine] INFO: Spider closed (finished)
2023-09-22 21:12:50 [scrapy-playwright] INFO: Closing download handler
2023-09-22 21:12:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method DownloadHandlers._close of <scrapy.core.downloader.handlers.DownloadHandlers object at 0x00000251E6844D50>>
Traceback (most recent call last):
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\twisted\internet\defer.py", line 1693, in _inlineCallbacks
    result = context.run(
             ^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\twisted\python\failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 92, in _close
    yield dh.close()
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\twisted\internet\defer.py", line 1693, in _inlineCallbacks
    result = context.run(
             ^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\twisted\python\failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\scrapy_playwright\handler.py", line 277, in close
    yield deferred_from_coro(self._close())
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
                ^^^^^^^^^^^^^^^
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\scrapy_playwright\handler.py", line 285, in _close
    await self.playwright_context_manager.__aexit__()
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\async_api\_context_manager.py", line 58, in __aexit__
    await self._connection.stop_async()
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\_impl\_connection.py", line 282, in stop_async
    self._transport.request_stop()
  File "C:\Users\emilr\Code\projects\work\freelance\data_mine\venv\Lib\site-packages\playwright\_impl\_transport.py", line 101, in request_stop
    assert self._output
           ^^^^^^^^^^^^
AttributeError: 'PipeTransport' object has no attribute '_output'
```

**Comment by elacuesta** [comment]
[This package does not work natively on Windows](https://github.com/scrapy-plugins/scrapy-playwright#lack-of-native-support-for-windows).
