### ISSUE TITLE
AttributeError: 'ScrapyPlaywrightDownloadHandler' object has no attribute 'contexts'

### ISSUE THREAD

**Issue by jeroenvermunt** [scrapy-plugins/scrapy-playwright#50]
Hey there,

I wanted to try and get started with playwright, and what I did to start off was simply add the meta = {'playwright':True} arguments to the scrapy.Request in an already working spider.

However, now the spider immediately stops working and gives the error:
````AttributeError: 'ScrapyPlaywrightDownloadHandler' object has no attribute 'contexts'````

I already added the following lines to the settings.py of my script:
````
DOWNLOAD_HANDLERS = {
    "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
    "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
}

TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
````
Full log:
````
2022-01-21 19:12:47 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method DownloadHandlers._close of <scrapy.core.downloader.handlers.DownloadHandlers object at 0x7fcddf904220>>
Traceback (most recent call last):
  File "/home/jeroen/anaconda3/envs/scratch/lib/python3.8/site-packages/twisted/internet/defer.py", line 1657, in _inlineCallbacks
    result = current_context.run(
  File "/home/jeroen/anaconda3/envs/scratch/lib/python3.8/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/jeroen/anaconda3/envs/scratch/lib/python3.8/site-packages/scrapy/core/downloader/handlers/__init__.py", line 81, in _close
    yield dh.close()
  File "/home/jeroen/anaconda3/envs/scratch/lib/python3.8/site-packages/twisted/internet/defer.py", line 1657, in _inlineCallbacks
    result = current_context.run(
  File "/home/jeroen/anaconda3/envs/scratch/lib/python3.8/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/jeroen/anaconda3/envs/scratch/lib/python3.8/site-packages/scrapy_playwright/handler.py", line 146, in close
    yield deferred_from_coro(self._close())
  File "/home/jeroen/anaconda3/envs/scratch/lib/python3.8/site-packages/twisted/internet/defer.py", line 1031, in adapt
    extracted = result.result()
  File "/home/jeroen/anaconda3/envs/scratch/lib/python3.8/site-packages/scrapy_playwright/handler.py", line 149, in _close
    self.contexts.clear()
AttributeError: 'ScrapyPlaywrightDownloadHandler' object has no attribute 'contexts'
````

Seems something is wrong with my setup, anyone got an idea where the issue lies?

**Comment by b5y** [comment]
Have you tried to install python requirements?

```bash
playwright
scrapy-playwright
Scrapy
```

And then run in the terminal

```bash
playwright install
```

Some useful linkes:
1. [scrapy-playwright examples](https://github.com/scrapy-plugins/scrapy-playwright/tree/master/examples)
2. [scrapy-playwright in Docker](https://github.com/elacuesta/scrapy-playwright-cloud-example)

**Comment by jeroenvermunt** [comment]
I had only installed the python requirements, but I forgot to run playwright install in console. Thanks for the support.

**Comment by elacuesta** [comment]
Seems resolved, thanks for the intervention @b5y 🙌

**Comment by elacuesta** [comment]
This is most likely caused by a previous exception preventing the handler from being initialized successfully, causing the closing method to fail because the `contexts` attribute was not set. The actual exception happened before (in this case it was probably the fact that `playwright` was not installed), but this message is still confusing. Hopefully it would not be a problem after 023b35d3a9b2c8570580dca743d3292d943c8217.
