### ISSUE TITLE
KeyError: 'playwright_page' when using errback

### ISSUE THREAD

**Issue by anvaari** [scrapy-plugins/scrapy-playwright#82]
Hi again.
As you mentioned in doc, I try to close page when error occurred. but this exception raise : 
```python
2022-04-26 11:54:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://play.google.com/store/apps/details?id=zzzee.erialsee.howsips> (referer: https://play.google.com/)
Traceback (most recent call last):
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/twisted/internet/defer.py", line 1030, in adapt
    extracted = result.result()
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/GooglePlay/GPlay_Scraper/GPlay_Scraper/spiders/google_play.py", line 142, in errback
    page = failure.request.meta["playwright_page"]
KeyError: 'playwright_page'
```
I implement errback same as doc : 
```python
# In start_requests : 
yield Request(url,
                              callback=self.parse,
                              meta=dict(
                                    playwright=True,
                                    playwright_include_page= True,
                                    playwright_page_methods={
                                        "click": PageMethod("click", selector=#some_selector#),
                                        "wait_for_win": PageMethod("wait_for_selector", #some_selector)
                                    }),
                              cb_kwargs=dict(#some_kwarg),
                              errback=self.errback)
# errback function 
 async def errback(self, failure):
        page = failure.request.meta["playwright_page"]
        await page.close()
```

**Comment by elacuesta** [comment]
Are there any previous exceptions in the logs? I'm thinking something before [this line](https://github.com/scrapy-plugins/scrapy-playwright/blob/v0.0.14/scrapy_playwright/handler.py#L260) might have failed.

**Comment by anvaari** [comment]
@elacuesta Yes, `wait_for_win` leading to `TimeoutError` : 
```python
2022-04-26 11:54:53 [scrapy.core.scraper] ERROR: Error downloading <GET https://play.google.com/store/apps/details?id=zzzee.erialsee.howsips>
Traceback (most recent call last):
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/scrapy/core/downloader/middleware.py", line 44, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/twisted/internet/defer.py", line 1030, in adapt
    extracted = result.result()
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/scrapy_playwright/handler.py", line 241, in _download_request
    result = await self._download_request_with_page(request, page)
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/scrapy_playwright/handler.py", line 254, in _download_request_with_page
    await self._apply_page_methods(page, request)
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/scrapy_playwright/handler.py", line 310, in _apply_page_methods
    pm.result = await result if isawaitable(result) else result
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 8297, in click
    await self._async(
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/playwright/_impl/_page.py", line 669, in click
    return await self._main_frame.click(**locals_to_params(locals()))
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/playwright/_impl/_frame.py", line 460, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "//h2[text()='Additional Information']/../..//div[text()='Permissions']/..//a"
============================================================
2022-04-26 11:54:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://play.google.com/store/apps/details?id=zzzee.erialsee.howsips> (referer: https://play.google.com/)
Traceback (most recent call last):
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/CaffeBazar/Bazar_Scraper/.env38/lib/python3.8/site-packages/twisted/internet/defer.py", line 1030, in adapt
    extracted = result.result()
  File "/home/anvaari/Work/Pezhoheshgah/Tasks/GooglePlay/GPlay_Scraper/GPlay_Scraper/spiders/google_play.py", line 142, in errback
    page = failure.request.meta["playwright_page"]
KeyError: 'playwright_page'
```

**Comment by elacuesta** [comment]
#91 aims to fix this issue. It also updates the Readme to clarify that it's only necessary to use an errback when passing `include_playwright_page=True`, otherwise the handler itself closes pages when exceptions occur. This means that if you're not actually using the page in your callback, it's best not to use `include_playwright_page`.
