### ISSUE TITLE
AttributeError: 'PipeTransport' object has no attribute '_output'

### ISSUE THREAD

**Issue by tarek-kerbedj** [scrapy-plugins/scrapy-playwright#90]
2022-05-08 19:30:45 [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:191> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 198, in run
    await self._transport.connect()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 140, in connect
    raise exc
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 128, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2022-05-08 19:30:45 [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-4' coro=<Connection.run() done, defined at C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:191> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 198, in run
    await self._transport.connect()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 140, in connect
    raise exc
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 128, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2022-05-08 19:30:45 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ScrapyPlaywrightDownloadHandler._engine_started of <scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler object at 0x000001CD8090A620>>
Traceback (most recent call last):
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 1030, in adapt
    extracted = result.result()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy_playwright\handler.py", line 127, in _launch_browser
    self.playwright = await self.playwright_context_manager.start()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 198, in run
    await self._transport.connect()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 140, in connect
    raise exc
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 128, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2022-05-08 19:30:45 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ScrapyPlaywrightDownloadHandler._engine_started of <scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler object at 0x000001CD80EE9450>>
Traceback (most recent call last):
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 1030, in adapt
    extracted = result.result()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy_playwright\handler.py", line 127, in _launch_browser
    self.playwright = await self.playwright_context_manager.start()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 198, in run
    await self._transport.connect()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 140, in connect
    raise exc
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 128, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2022-05-08 19:30:50 [filelock] DEBUG: Attempting to acquire lock 1982164440720 on C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\tldextract\.suffix_cache/publicsuffix.org-tlds\de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2022-05-08 19:30:50 [filelock] DEBUG: Lock 1982164440720 acquired on C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\tldextract\.suffix_cache/publicsuffix.org-tlds\de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2022-05-08 19:30:50 [filelock] DEBUG: Attempting to acquire lock 1982164450560 on C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\tldextract\.suffix_cache/urls\62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
2022-05-08 19:30:50 [filelock] DEBUG: Lock 1982164450560 acquired on C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\tldextract\.suffix_cache/urls\62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
2022-05-08 19:30:50 [filelock] DEBUG: Attempting to release lock 1982164450560 on C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\tldextract\.suffix_cache/urls\62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
2022-05-08 19:30:50 [filelock] DEBUG: Lock 1982164450560 released on C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\tldextract\.suffix_cache/urls\62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
2022-05-08 19:30:50 [filelock] DEBUG: Attempting to release lock 1982164440720 on C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\tldextract\.suffix_cache/publicsuffix.org-tlds\de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2022-05-08 19:30:50 [filelock] DEBUG: Lock 1982164440720 released on C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\tldextract\.suffix_cache/publicsuffix.org-tlds\de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2022-05-08 19:30:50 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://yandex.com/robots.txt> (referer: None)
2022-05-08 19:30:50 [scrapy.downloadermiddlewares.robotstxt] DEBUG: Forbidden by robots.txt: <GET https://yandex.com/images/search?text=kanye%20west>
2022-05-08 19:30:50 [scrapy.core.engine] INFO: Closing spider (finished)
2022-05-08 19:30:50 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/scrapy.exceptions.IgnoreRequest': 1,
 'downloader/request_bytes': 220,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 2679,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 5.686958,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2022, 5, 8, 17, 30, 50, 750869),
 'httpcompression/response_bytes': 10462,
 'httpcompression/response_count': 1,
 'log_count/DEBUG': 13,
 'log_count/ERROR': 4,
 'log_count/INFO': 10,
 'response_received_count': 1,
 'robotstxt/forbidden': 1,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2022, 5, 8, 17, 30, 45, 63911)}
2022-05-08 19:30:50 [scrapy.core.engine] INFO: Spider closed (finished)
2022-05-08 19:30:50 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method DownloadHandlers._close of <scrapy.core.downloader.handlers.DownloadHandlers object at 0x000001CD80908550>>
Traceback (most recent call last):
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\python\failure.py", line 489, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 81, in _close
    yield dh.close()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\python\failure.py", line 489, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy_playwright\handler.py", line 195, in close
    yield deferred_from_coro(self._close())
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 1030, in adapt
    extracted = result.result()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy_playwright\handler.py", line 203, in _close
    await self.playwright_context_manager.__aexit__()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 54, in __aexit__
    await self._connection.stop_async()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 208, in stop_async
    self._transport.request_stop()
  File "C:\Users\Oxidi\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 107, in request_stop
    assert self._output
AttributeError: 'PipeTransport' object has no attribute '_output'

I followed the installation guide step by step

**Comment by elacuesta** [comment]
#7

**Comment by HamzaBouajila007** [comment]
hello , have you figured the issue and how to solve it ?
