### ISSUE TITLE
Example when using LinkExtractor

### ISSUE THREAD

**Issue by chhenning** [scrapy-plugins/scrapy-playwright#99]
I'm trying to come up with a simple spider that takes a screenshot of every page. 

In the example below the `parse_item()` is called for every link. But then the `take_screenshot()` is not called at all. Perhaps, I missed something in the documentation?

```py
import hashlib
import logging
from typing import Generator

from scrapy.http import Response, Request
from scrapy.link import Link
from scrapy.spiders import CrawlSpider, Rule
from scrapy.crawler import CrawlerProcess
from scrapy.linkextractors import LinkExtractor
from scrapy.http.response import Response

from scrapy_playwright.page import PageMethod

DEBUG = False
logging.getLogger("scrapy").propagate = DEBUG
logging.getLogger("filelock").propagate = False


class AwesomeSpider(CrawlSpider):
    name = "page"

    custom_meta = {
        "playwright": True,
        "playwright_context": 1,
        "playwright_include_page": True,
        "playwright_page_methods": [
            PageMethod("wait_for_load_state", "networkidle"),
        ],
    }

    def __init__(self, **kw):
        self.rules = (
            Rule(
                LinkExtractor(),
                process_links="process_links",
                callback="parse_item",
                follow=True,
            ),
        )

        super().__init__(**kw)

    def process_links(self, links: list[Link]) -> list[Link]:
        return links

    def parse_item(self, response: Response):
        yield Request(
            response.url,
            callback=self.take_screenshot,
            meta=self.custom_meta,
        )

    async def take_screenshot(self, response):
        print(response.url)
        page = response.meta.get("playwright_page")
        if page:
            url_sha256 = hashlib.sha256(response.url.encode("utf-8")).hexdigest()
            page = response.meta["playwright_page"]
            await page.screenshot(path=f"{url_sha256}.png", full_page=True)
            title = await page.title()
            await page.close()
            return {"url": response.url, "title": title}

    async def errback(self, failure):
        page = failure.request.meta.get("playwright_page")
        if page:
            await page.close()


if __name__ == "__main__":
    process = CrawlerProcess(
        settings={
            "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
            "DOWNLOAD_HANDLERS": {
                "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
                "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
            },
            "CONCURRENT_REQUESTS": 32,
            "PLAYWRIGHT_MAX_PAGES_PER_CONTEXT": 4,
            "CLOSESPIDER_ITEMCOUNT": 100,
            "TELNETCONSOLE_ENABLED": False,
            "FEEDS": {
                "data.json": {
                    "format": "json",
                    "encoding": "utf-8",
                    "indent": 4,
                },
            },
        }
    )

    process.crawl(
        AwesomeSpider,
        allowed_domains=["toscrape.com"],
        start_urls=["https://books.toscrape.com/"],
    )
    logging.getLogger("scrapy.core.engine").setLevel(logging.WARNING)
    logging.getLogger("scrapy.core.scraper").setLevel(logging.WARNING)
    process.start()
```

**Comment by elacuesta** [comment]
In `parse_item` you're yielding a new request to an URL which has already been crawled, so it gets discarded by the [dupefilter](https://docs.scrapy.org/en/latest/topics/settings.html#dupefilter-class). Possible alternatives are:
1. Pass `dont_filter=True` to the `Request` object. Not a very good solution, you would be downloading the same resource twice.
2. Take the screenshot in the first callback. I haven't tried it but I suspect it won't work, I don't think `CrawlSpider` currently supports `async def` callbacks - [source](https://github.com/scrapy/scrapy/blob/2.6/scrapy/spiders/crawl.py#L114).
3. Take the screenshot using a `PageMethod` object. This way you won't have access to the `page.url` to construct the screenshot file name, the closest thing I can think of is using a `Rule.process_request` and create the `PageMethod` there based on the `request.url` attribute (`page.url` might be different than `request.url`, for instance in a redirect, but it might be an acceptable compromise).

**Comment by chhenning** [comment]
The first alternative is working quite nicely, even though as you stated it would redownload the resource. The change is simply: 

```py
  def parse_item(self, response: Response):
      yield Request(
          response.url,
          callback=self.take_screenshot,
          meta=self.custom_meta,
          dont_filter=True,
      )
```

As for the thirs option. Is this what you had in mind?

```py
import hashlib
import logging
from typing import Generator

from scrapy.http import Response, Request
from scrapy.link import Link
from scrapy.spiders import CrawlSpider, Rule
from scrapy.crawler import CrawlerProcess
from scrapy.linkextractors import LinkExtractor
from scrapy.http.response import Response

from scrapy_playwright.page import PageMethod

DEBUG = False
logging.getLogger("scrapy").propagate = DEBUG
logging.getLogger("filelock").propagate = False


class AwesomeSpider(CrawlSpider):
    name = "page"

    def __init__(self, **kw):

        self.rules = (
            Rule(
                LinkExtractor(),
                process_request="process_item",
                follow=True,
            ),
        )

        super().__init__(**kw)

    def process_item(self, request: Request, response: Response):
        url_sha256 = hashlib.sha256(request.url.encode("utf-8")).hexdigest()

        my_meta = {
            "playwright": True,
            "playwright_context": 1,
            "playwright_include_page": True,
            "playwright_page_methods": [
                PageMethod("wait_for_load_state", "networkidle"),
                PageMethod("screenshot", path=f"{url_sha256}.png", fullPage=True),
            ],
        }

        return Request(
            request.url,
            meta=my_meta,
        )


if __name__ == "__main__":
    process = CrawlerProcess(
        settings={
            "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
            "DOWNLOAD_HANDLERS": {
                "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
                "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
            },
            "CONCURRENT_REQUESTS": 32,
            "PLAYWRIGHT_MAX_PAGES_PER_CONTEXT": 4,
            "CLOSESPIDER_ITEMCOUNT": 10,
            "TELNETCONSOLE_ENABLED": False,
            "FEEDS": {
                "data.json": {
                    "format": "json",
                    "encoding": "utf-8",
                    "indent": 4,
                },
            },
        }
    )

    process.crawl(
        AwesomeSpider,
        allowed_domains=["toscrape.com"],
        start_urls=["https://books.toscrape.com/"],
    )
    logging.getLogger("scrapy.core.engine").setLevel(logging.WARNING)
    logging.getLogger("scrapy.core.scraper").setLevel(logging.WARNING)
    process.start()
```
If so, then I'm getting this error:

```
Error downloading <GET https://books.toscrape.com/catalogue/category/books/contemporary_38/index.html>
Traceback (most recent call last):
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 49, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1030, in adapt
    extracted = result.result()
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 275, in _download_request
    result = await self._download_request_with_page(request, page)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 292, in _download_request_with_page
    await self._apply_page_methods(page, request)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 344, in _apply_page_methods
    pm.result = await _maybe_await(method(*pm.args, **pm.kwargs))
TypeError: Page.screenshot() got an unexpected keyword argument 'fullPage'
```

**Comment by sucream** [comment]
`Page.screenshot` function's argument is `full_page` not `fullPage`.

```python
PageMethod("screenshot", path=f"{url_sha256}.png", full_page=True),
```

**Comment by chhenning** [comment]
@sucream Correct! thanks. There seems to be the same type in the readme.

When I now run the script it takes 4 screenshots and becomes stuck while

```
[snip]
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/static/oscar/js/bootstrap3/bootstrap.min.js> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/static/oscar/js/oscar/ui.js> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.js> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/static/oscar/js/bootstrap-datetimepicker/locales/bootstrap-datetimepicker.all.js> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/static/oscar/fonts/fontawesome-webfont.woff%3Fv=3.2.1> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/static/oscar/js/jquery/jquery-1.9.1.min.js> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/static/oscar/js/jquery/jquery-1.9.1.min.js> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/static/oscar/js/jquery/jquery-1.9.1.min.js> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/static/oscar/fonts/fontawesome-webfont.woff%3Fv=3.2.1> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/static/oscar/js/jquery/jquery-1.9.1.min.js> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/static/oscar/fonts/fontawesome-webfont.woff%3Fv=3.2.1> (referrer: None)
2022-06-24 11:16:06 [scrapy-playwright] DEBUG: [Context=1] Response: <200 https://books.toscrape.com/static/oscar/fonts/fontawesome-webfont.woff%3Fv=3.2.1> (referrer: None)
```

When I terminate the process I get the following errors:

```
^C2022-06-24 11:18:32 [scrapy-playwright] DEBUG: Browser context closed: '1' (persistent=False)
Error downloading <GET https://books.toscrape.com/catalogue/category/books/business_35/index.html>
Traceback (most recent call last):
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 49, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1030, in adapt
    extracted = result.result()
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 247, in _download_request
    page = await self._create_page(request)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 190, in _create_page
    page = await context.context.new_page()
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 10450, in new_page
    await self._async("browser_context.new_page", self._impl_obj.new_page())
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_browser_context.py", line 199, in new_page
    return from_channel(await self._channel.send("newPage"))
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /Users/chhenning/Library/Caches/ms-playwright/chromium-1005/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/21/11qcwc4n1l1czxf5ztrzspgc0000gn/T/playwright_chromiumdev_profile-tYKYwl --remote-debugging-pipe --no-startup-window
<launched> pid=17005
[pid=17005][err] objc[17006]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb484ec948) and /Users/chhenning/Library/Caches/ms-playwright/chromium-1005/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/102.0.5005.40/Libraries/libGLESv2.dylib (0x10b13fe28). One of the two will be used. Which one is undefined.
[pid=17005] <gracefully close start>
Error downloading <GET https://books.toscrape.com/catalogue/category/books/christian-fiction_34/index.html>
Traceback (most recent call last):
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 49, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1030, in adapt
    extracted = result.result()
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 247, in _download_request
    page = await self._create_page(request)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 190, in _create_page
    page = await context.context.new_page()
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 10450, in new_page
    await self._async("browser_context.new_page", self._impl_obj.new_page())
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_browser_context.py", line 199, in new_page
    return from_channel(await self._channel.send("newPage"))
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /Users/chhenning/Library/Caches/ms-playwright/chromium-1005/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/21/11qcwc4n1l1czxf5ztrzspgc0000gn/T/playwright_chromiumdev_profile-tYKYwl --remote-debugging-pipe --no-startup-window
<launched> pid=17005
[pid=17005][err] objc[17006]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb484ec948) and /Users/chhenning/Library/Caches/ms-playwright/chromium-1005/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/102.0.5005.40/Libraries/libGLESv2.dylib (0x10b13fe28). One of the two will be used. Which one is undefined.
[pid=17005] <gracefully close start>
Error downloading <GET https://books.toscrape.com/catalogue/category/books/food-and-drink_33/index.html>
Traceback (most recent call last):
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 49, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1030, in adapt
    extracted = result.result()
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 247, in _download_request
    page = await self._create_page(request)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 190, in _create_page
    page = await context.context.new_page()
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 10450, in new_page
    await self._async("browser_context.new_page", self._impl_obj.new_page())
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_browser_context.py", line 199, in new_page
    return from_channel(await self._channel.send("newPage"))
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /Users/chhenning/Library/Caches/ms-playwright/chromium-1005/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/var/folders/21/11qcwc4n1l1czxf5ztrzspgc0000gn/T/playwright_chromiumdev_profile-tYKYwl --remote-debugging-pipe --no-startup-window
<launched> pid=17005
[pid=17005][err] objc[17006]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb484ec948) and /Users/chhenning/Library/Caches/ms-playwright/chromium-1005/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/102.0.5005.40/Libraries/libGLESv2.dylib (0x10b13fe28). One of the two will be used. Which one is undefined.
[pid=17005] <gracefully close start>
Error downloading <GET https://books.toscrape.com/catalogue/category/books/history_32/index.html>
Traceback (most recent call last):
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 49, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1030, in adapt
    extracted = result.result()
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 247, in _download_request
    page = await self._create_page(request)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 190, in _create_page
    page = await context.context.new_page()
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 10450, in new_page
    await self._async("browser_context.new_page", self._impl_obj.new_page())
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_browser_context.py", line 199, in new_page
    return from_channel(await self._channel.send("newPage"))
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
Error downloading <GET https://books.toscrape.com/catalogue/category/books/autobiography_27/index.html>
Traceback (most recent call last):
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 49, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1030, in adapt
    extracted = result.result()
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 247, in _download_request
    page = await self._create_page(request)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 185, in _create_page
    context = await self._create_browser_context(
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 161, in _create_browser_context
    context = await self.browser.new_context(**context_kwargs)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 11344, in new_context
    await self._async(
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_browser.py", line 117, in new_context
    channel = await self._channel.send("newContext", params)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
Error downloading <GET https://books.toscrape.com/catalogue/category/books/psychology_26/index.html>
Traceback (most recent call last):
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy/core/downloader/middleware.py", line 49, in process_request
    return (yield download_func(request=request, spider=spider))
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/twisted/internet/defer.py", line 1030, in adapt
    extracted = result.result()
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 247, in _download_request
    page = await self._create_page(request)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 185, in _create_page
    context = await self._create_browser_context(
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/scrapy_playwright/handler.py", line 161, in _create_browser_context
    context = await self.browser.new_context(**context_kwargs)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 11344, in new_context
    await self._async(
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_browser.py", line 117, in new_context
    channel = await self._channel.send("newContext", params)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/Users/chhenning/.pyenv/versions/cooper/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
```




Here is the latest.

```py
import hashlib
import logging
from typing import Generator

from scrapy.http import Response, Request
from scrapy.link import Link
from scrapy.spiders import CrawlSpider, Rule
from scrapy.crawler import CrawlerProcess
from scrapy.linkextractors import LinkExtractor
from scrapy.http.response import Response

from scrapy_playwright.page import PageMethod

DEBUG = False
logging.getLogger("scrapy").propagate = DEBUG
logging.getLogger("filelock").propagate = False


class AwesomeSpider(CrawlSpider):
    name = "page"

    def __init__(self, **kw):

        self.rules = (
            Rule(
                LinkExtractor(),
                process_request="process_item",
                follow=True,
            ),
        )

        super().__init__(**kw)

    def process_item(self, request: Request, response: Response):
        url_sha256 = hashlib.sha256(request.url.encode("utf-8")).hexdigest()

        my_meta = {
            "playwright": True,
            "playwright_context": 1,
            "playwright_include_page": True,
            "playwright_page_methods": [
                PageMethod("wait_for_load_state", "networkidle"),
                PageMethod("screenshot", path=f"{url_sha256}.png", full_page=True),
            ],
        }

        return Request(
            request.url,
            meta=my_meta,
        )


if __name__ == "__main__":
    process = CrawlerProcess(
        settings={
            "TWISTED_REACTOR": "twisted.internet.asyncioreactor.AsyncioSelectorReactor",
            "DOWNLOAD_HANDLERS": {
                "https": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
                "http": "scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler",
            },
            "CONCURRENT_REQUESTS": 32,
            "PLAYWRIGHT_MAX_PAGES_PER_CONTEXT": 4,
            "CLOSESPIDER_ITEMCOUNT": 10,
            "TELNETCONSOLE_ENABLED": False,
            "FEEDS": {
                "data.json": {
                    "format": "json",
                    "encoding": "utf-8",
                    "indent": 4,
                },
            },
        }
    )

    process.crawl(
        AwesomeSpider,
        allowed_domains=["toscrape.com"],
        start_urls=["https://books.toscrape.com/"],
    )
    process.start()
```

**Comment by elacuesta** [comment]
Fixed the camel case argument occurrences in the readme, thanks for pointing those out.

Regarding the spider getting stuck, you're passing `playwright_include_page=True` so pages are not closed by the downloader, causing the limit set by `PLAYWRIGHT_MAX_PAGES_PER_CONTEXT=4` to be reached. From [the readme](https://github.com/scrapy-plugins/scrapy-playwright/blob/master/README.md#receiving-page-objects-in-callbacks):

> Be careful about leaving pages unclosed, as they count towards the limit set by PLAYWRIGHT_MAX_PAGES_PER_CONTEXT.

I just updated the readme to be even more explicit about this (55102c5ae0f1e4330fdfd5fbd10e3bbfca4d9ca7)

**Comment by elacuesta** [comment]
All questions have been answered and there hasn't been new activity in more than a month, closing.
